version: '3'

services:
  scylla:
    container_name: 'scyllaDB'
    image: 'scylladb/scylla'
    restart: always
    networks:
      - custom-b
    ports:
      - "0.0.0.0:9042:9042"
      - "0.0.0.0:9160:9160"

  ipfs:
    container_name: 'ipfs'
    image: 'ipfs/go-ipfs:v0.19.1'
    environment:
      - LIBP2P_FORCE_PNET=1
    restart: always
    command: "daemon --enable-pubsub-experiment"
    networks:
      - custom-b
    ports:
      - "4001:4001"
      - "5001:5001"
      - "8080:8080"
    volumes:
    - ./ipfs/swarm.key:/data/ipfs/swarm.key
    - ./ipfs/init-priv.sh:/container-init.d/001-init-priv.sh
    - ./configuration/config.env:/config.env

  orbitdb:
    container_name: 'orbitdb'
    build: ./orbit_node/
    restart: always
    environment:
      IPFS: ipfs
    command: node orbit_api --orbitdb-dir /root/orbitdb
    networks:
      - custom-b
    ports:
      - "0.0.0.0:3000:3000"

  rest_api:
    container_name: 'restapi_service'
    build: ./rest_api/
    environment:
      DB_HOST: scylla
      ORBIT_HOST: orbitdb
      GANACHE_HOST: truffle
      #VAULT_HOST: vault
    ports:
      - "8000:8000"
    volumes:
      - ./rest_api/app:/root/service
      #- ./rest_api/profiler:/tmp/profiler
    networks:
      - custom-b

  truffle:
    container_name: 'truffle'
    image: 'trufflesuite/ganache:latest'
    networks:
      - custom-b
    ports:
      - "8545:8545"

networks:
  custom-b:
    driver: bridge